# define these variables here if necessary or define them as environment variables
BOOST_INCLUDE_DIR = /usr/include
BOOST_LIB_DIR = /usr/lib
# optionally define compiler to use
CC = cc -Wno-error=misleading-indentation -Wno-error=unused-local-typedefs -Wno-error=deprecated -Wno-error=unused-function -DBOOST_MESSAGE=BOOST_TEST_MESSAGE
# internal variable definitions
TORC_1_0_ENABLE_VERILOG = 0
